In [1]:
import pandas as pd
counts = pd.read_csv('norm_counts.csv')
counts.head()

   paper_subject  reference_subject  norm_counts
0             10               10.0     0.000000
1             10               11.0     0.008153
2             10               12.0     0.000008
3             10               13.0     0.102940
4             10               15.0     0.000792

In [2]:
type(counts.iloc[0,0])

numpy.int64

In [6]:
counts['reference_subject'] = counts['reference_subject'].astype(int)
counts

     paper_subject  reference_subject  norm_counts
0               10                 10     0.000000
1               10                 11     0.008153
2               10                 12     0.000008
3               10                 13     0.102940
4               10                 15     0.000792
5               10                 16     0.005156
6               10                 17     0.000509
7               10                 19     0.000308
8               10                 20     0.000018
9               10                 22     0.000532
10              10                 23     0.000866
11              10                 24     0.052153
12              10                 25     0.000372
13              10                 26     0.001012
14              10                 27     0.064692
15              10                 28     0.132505
16              10                 29     0.003830
17              10                 30     0.060035
18              10                 31     0.067241
19              10                 32     0.112775
20              10                 33     0.058085
21              10                 34     0.094254
22              10                 35     0.072844
23              10                 36     0.160919
24              11                 10     0.041358
25              11                 11     0.000000
26              11                 12     0.000043
27              11                 13     0.113343
28              11                 14     0.000004
29              11                 15     0.001176
..             ...                ...          ...
595             35                 31     0.035258
596             35                 32     0.078798
597             35                 33     0.102884
598             35                 34     0.055704
599             35                 35     0.000000
600             35                 36     0.209485
601             36                 10     0.002106
602             36                 11     0.001312
603             36                 12     0.000371
604             36                 13     0.006730
605             36                 15     0.000067
606             36                 16     0.000292
607             36                 17     0.007459
608             36                 19     0.000094
609             36                 20     0.000006
610             36                 22     0.007395
611             36                 23     0.000273
612             36                 24     0.000553
613             36                 25     0.000117
614             36                 26     0.000672
615             36                 27     0.182357
616             36                 28     0.064503
617             36                 29     0.063423
618             36                 30     0.007556
619             36                 31     0.045723
620             36                 32     0.151219
621             36                 33     0.195756
622             36                 34     0.034709
623             36                 35     0.227308
624             36                 36     0.000000

[625 rows x 3 columns]

In [7]:
counts.to_csv('norm_counts_new.csv', index = False)